#!/bin/bash

if [ ! -d "build/.git" ]; then
  echo "Please run the setup script before first deployment."
  exit
fi

middleman build
ruby script/generate_json.rb

cd build

git add .
git commit -m "Deployment `date`"
git push prod +master